---
kind: Service
apiVersion: v1
metadata:
  name: helloworldservice
spec:
  selector:
    # defined on deployment below
    app: hello-world # Target the pod named hello-world
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      # 8080 -> 80
      port: 8080
      # Port to forward to inside the pod
      # This is the default port for web servers
      targetPort: 80
      # Port accessible outside cluster
      # 30001 -> 80
      nodePort: 30001
  type: LoadBalancer


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world # Name of the deployment you want
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: hello-world # Name of the app you want
    spec:
      containers:
          # Pulls image from the registry
          # To avoid pulling from the registry
          # See enabling minikube docker daemon
        - name: hello-world # Name of the image you want
          image: tutum/hello-world # The actual image name from the registry
          ports:
            - containerPort: 80