kind: Service
apiVersion: v1
metadata:
  name: django-service
spec:
  selector:
    pod: django-deployment # expose this key:value pair name
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort