kind: Service
apiVersion: v1
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres-container # refers to key:value defined in the postgres_deployment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432