---
- hosts: localhost
  tasks:
    - name: Include variables
      include_vars:
        file: vars.yml
        name: xvar
      tags: var

    - name: Check if pamac is installed
      command: which pamac
      register: pamac
      tags: base

    - name: Check updates with pamac
      command: pamac checkupdates
      register: updates
      when: pamac.rc == 0
      failed_when: updates.stderr != ""
      tags: base

    - name: Update with pamac
      command: pamac upgrade --no-confirm
      become: yes
      when:
        - pamac.rc == 0
        - updates.rc > 0
      tags: base

    - name: Install yay
      command: pamac install yay --no-confirm
      become: yes
      tags: base

    - name: Install code
      command: pamac install code --no-confirm
      become: yes
      tags:
        - dev
        - long

    - name: Install terminator
      command: pamac install terminator --no-confirm
      register: terminator
      become: yes
      tags: dev

    - name: Install vim
      command: pamac install vim --no-confirm
      become: yes
      tags:
        - dev
        - shell

    - name: Install zsh
      command: pamac install zsh zsh-completions --no-confirm
      register: zsh
      become: yes
      notify:
        - Change shell to zsh
      tags:
        - dev
        - shell

    - name: Install oh-my-zsh
      command: /usr/bin/wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
      args:
        chdir: "{{ ansible_env.HOME }}"
      notify:
        - Run install.sh
        - Set zsh theme
        - Remove install.sh
      tags:
        - dev
        - shell

    - name: Install git
      command: pamac install git --no-confirm
      become: yes
      notify:
        - Setup git configurations
        - Create git log alias
        - Generate rsa keys
      tags:
        - dev
        - shell

    - name: Install docker
      command: pamac install docker --no-confirm
      become: yes
      tags:
        - dev
        - docker

    - name: Download docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ xvar.docker_compose_version }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: +x
      become: yes
      tags:
        - dev
        - docker

    - name: Install nvm
      shell: >
        curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/{{ xvar.nvm_version }}/install.sh" | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      notify:
        - Add nvm to path
        - Load nvm
        - Load bash completion
      tags:
        - dev
        - node

    - name: Install latest node
      shell: ". {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install node"
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/versions/node"
        chdir: "{{ ansible_env.HOME }}"
        executable: /bin/zsh
      tags:
        - dev
        - node

    - name: Remove golang file
      file:
        path: "{{ ansible_env.HOME }}/Downloads/golang.tar.gz"
        state: absent
      tags: golang

    - name: Install Golang
      get_url:
        url: "https://dl.google.com/go/{{ xvar.golang_version }}.linux-amd64.tar.gz"
        dest: "{{ ansible_env.HOME }}/Downloads/golang.tar.gz"
      notify:
        - Extract golang
        - Remove golang tgz
        - Add go root to path
        - Add go path to path
      tags:
        - dev
        - golang

  handlers:
    - name: Change shell to zsh
      command: chsh -s /usr/bin/zsh
      become: yes
      when: zsh is success

    - name: Add nvm to path
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        state: present
        line: export NVM_DIR="{{ ansible_env.HOME }}/.nvm"

    - name: Load nvm
      lineinfile:
        path: ~/.zshrc
        state: present
        line: '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'

    - name: Load bash completion
      lineinfile:
        path: ~/.zshrc
        state: present
        line: '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'

    - name: Run install.sh
      command: /usr/bin/sh "{{ ansible_env.HOME }}/install.sh"
      register: install
      failed_when:
        - install.rc|int > 0
        - install.stderr != ""

    - name: Set zsh theme
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        state: present
        regexp: "^ZSH_THEME=.*"
        line: 'ZSH_THEME="ys"'

    - name: Remove install.sh
      file:
        path: "{{ ansible_env.HOME }}/install.sh"
        state: absent

    - name: Setup git configurations
      command: "git config --global {{ item }}"
      with_items:
        - user.name "{{ xvar.user }}"
        - user.email "{{ xvar.email }}"
        - color.ui auto
        - color.branch auto
        - color.diff auto
        - color.status auto

    - name: Create git log alias
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        state: present
        line: 'alias glog="git log --graph --all --pretty=format:''%C(blue)%h %C(red)%d %Creset - %C(yellow)%s%Creset %C(green)(%cr)%Creset <%aN>''"'

    - name: Generate rsa keys
      command: /usr/bin/ssh-keygen -t rsa -N '' -b 4096 -C '{{ xvar.email }}' -f "{{ ansible_env.HOME }}/.ssh/id_rsa"
      args:
        creates: "{{ ansible_env.HOME }}/.ssh/id_rsa"

    - name: Extract golang
      unarchive:
        src: "{{ ansible_env.HOME }}/Downloads/golang.tar.gz"
        dest: "{{ ansible_env.HOME }}/Downloads"

    - name: Add go root to path
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        state: present
        line: "PATH=$PATH:{{ xvar.golang_root_path }}/bin"

    - name: Add go path to path
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        state: present
        line: "PATH=$PATH:{{ xvar.golang_app_path}}/bin"

    - name: Remove golang tgz
      file:
        path: "{{ ansible_env.HOME }}/Downloads/golang.tar.gz"
        state: absent
